# fly.toml app configuration file generated for researchcrm-redis on 2023-09-03T23:11:12+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "researchcrm-redis"
primary_region = "sin"

[build]
  image = "flyio/redis:6.2.6"

[[mounts]]
  source = "redis_server"
  destination = "/data"
